import type { AfricaRegion, Quote } from "./quoteTypes";

const makeId = (region: AfricaRegion, n: number) =>
  `${region.toLowerCase()}-${String(n).padStart(3, "0")}`;

export const QUOTES: Quote[] = [
  // WEST (40)
  {
    id: makeId("West", 1),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "Wisdom is like a baobab tree; no one individual can embrace it.",
    tags: ["wisdom", "community"],
    source: "Traditional",
  },
  {
    id: makeId("West", 2),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "The child who is not embraced by the village will burn it down to feel its warmth.",
    tags: ["community", "belonging"],
    source: "Traditional",
  },
  {
    id: makeId("West", 3),
    region: "West",
    country: "Nigeria",
    origin: "Igbo",
    author: "Igbo Proverb",
    text: "When the moon is shining the cripple becomes hungry for a walk.",
    tags: ["opportunity", "motivation"],
    source: "Traditional",
  },
  {
    id: makeId("West", 4),
    region: "West",
    country: "Senegal",
    origin: "Wolof",
    author: "Wolof Proverb",
    text: "Patience can cook a stone.",
    tags: ["patience", "perseverance"],
    source: "Traditional",
  },
  {
    id: makeId("West", 5),
    region: "West",
    country: "Mali",
    origin: "Bambara",
    author: "Bambara Proverb",
    text: "However long the night, the dawn will break.",
    tags: ["hope", "resilience"],
    source: "Traditional",
  },
  {
    id: makeId("West", 6),
    region: "West",
    country: "Sierra Leone",
    origin: "Mende",
    author: "Mende Proverb",
    text: "When spider webs unite, they can tie up a lion.",
    tags: ["unity", "strength"],
    source: "Traditional",
  },
  {
    id: makeId("West", 7),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "A person who asks questions does not lose their way.",
    tags: ["learning", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("West", 8),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "The ruin of a nation begins in the homes of its people.",
    tags: ["society", "responsibility"],
    source: "Traditional",
  },
  {
    id: makeId("West", 9),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "No matter how long the log stays in the water, it does not become a crocodile.",
    tags: ["identity", "authenticity"],
    source: "Traditional",
  },
  {
    id: makeId("West", 10),
    region: "West",
    country: "Gambia",
    origin: "Mandinka",
    author: "Mandinka Proverb",
    text: "If you climb a good tree, you deserve a push.",
    tags: ["support", "encouragement"],
    source: "Traditional",
  },
  {
    id: makeId("West", 11),
    region: "West",
    country: "Nigeria",
    origin: "Igbo",
    author: "Igbo Proverb",
    text: "A toad does not run in the daytime for nothing.",
    tags: ["awareness", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("West", 12),
    region: "West",
    country: "Benin",
    origin: "Fon",
    author: "Fon Proverb",
    text: "The chameleon changes color to match the earth; the earth does not change color to match the chameleon.",
    tags: ["adaptation", "identity"],
    source: "Traditional",
  },
  {
    id: makeId("West", 13),
    region: "West",
    country: "Liberia",
    origin: "Kpelle",
    author: "Kpelle Proverb",
    text: "It is the calm and silent water that drowns a man.",
    tags: ["caution", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("West", 14),
    region: "West",
    country: "Burkina Faso",
    origin: "Mossi",
    author: "Mossi Proverb",
    text: "One falsehood spoils a thousand truths.",
    tags: ["truth", "integrity"],
    source: "Traditional",
  },
  {
    id: makeId("West", 15),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "The sun will shine on those who stand before it shines on those who kneel under them.",
    tags: ["leadership", "justice"],
    source: "Traditional",
  },
  {
    id: makeId("West", 16),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "By trying often, the monkey learns to jump from the tree.",
    tags: ["practice", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("West", 17),
    region: "West",
    country: "Nigeria",
    origin: "Igbo",
    author: "Igbo Proverb",
    text: "A man who makes trouble for others is also making it for himself.",
    tags: ["consequence", "character"],
    source: "Traditional",
  },
  {
    id: makeId("West", 18),
    region: "West",
    country: "Mali",
    origin: "Fulani",
    author: "Fulani Proverb",
    text: "River water does not flow past a sleeping frog.",
    tags: ["opportunity", "awareness"],
    source: "Traditional",
  },
  {
    id: makeId("West", 19),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "The one who climbs a ladder must begin at the bottom.",
    tags: ["humility", "progress"],
    source: "Traditional",
  },
  {
    id: makeId("West", 20),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "A wise person listens before speaking.",
    tags: ["wisdom", "communication"],
    source: "Traditional",
  },
  {
    id: makeId("West", 21),
    region: "West",
    country: "Senegal",
    origin: "Wolof",
    author: "Wolof Proverb",
    text: "One day in the life of a lion is worth more than a hundred years in the life of a sheep.",
    tags: ["courage", "boldness"],
    source: "Traditional",
  },
  {
    id: makeId("West", 22),
    region: "West",
    country: "Nigeria",
    origin: "Igbo",
    author: "Igbo Proverb",
    text: "He who brings kola brings life.",
    tags: ["hospitality", "tradition"],
    source: "Traditional",
  },
  {
    id: makeId("West", 23),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "The path does not close in front of the traveler.",
    tags: ["hope", "journey"],
    source: "Traditional",
  },
  {
    id: makeId("West", 24),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "Where there are elders, a child does not break his leg.",
    tags: ["guidance", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("West", 25),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "The fowl does not forget where it lays its eggs.",
    tags: ["memory", "roots"],
    source: "Traditional",
  },
  {
    id: makeId("West", 26),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "A tree cannot make a forest.",
    tags: ["unity", "community"],
    source: "Traditional",
  },
  {
    id: makeId("West", 27),
    region: "West",
    country: "Sierra Leone",
    origin: "Temne",
    author: "Temne Proverb",
    text: "The mouth that eats salt cannot avoid thirst.",
    tags: ["consequence", "choices"],
    source: "Traditional",
  },
  {
    id: makeId("West", 28),
    region: "West",
    country: "Nigeria",
    origin: "Igbo",
    author: "Igbo Proverb",
    text: "A man who lives in the marketplace must not be afraid of noise.",
    tags: ["resilience", "society"],
    source: "Traditional",
  },
  {
    id: makeId("West", 29),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "The good soup attracts many guests.",
    tags: ["generosity", "reputation"],
    source: "Traditional",
  },
  {
    id: makeId("West", 30),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "A child who washes his hands can eat with kings.",
    tags: ["discipline", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("West", 31),
    region: "West",
    country: "Benin",
    origin: "Fon",
    author: "Fon Proverb",
    text: "The wind does not break a tree that bends.",
    tags: ["flexibility", "resilience"],
    source: "Traditional",
  },
  {
    id: makeId("West", 32),
    region: "West",
    country: "Nigeria",
    origin: "Igbo",
    author: "Igbo Proverb",
    text: "The lizard that jumped from the high tree said it would praise itself if no one else did.",
    tags: ["confidence", "self-worth"],
    source: "Traditional",
  },
  {
    id: makeId("West", 33),
    region: "West",
    country: "Mali",
    origin: "Bambara",
    author: "Bambara Proverb",
    text: "Knowledge is like a garden; if it is not cultivated, it cannot be harvested.",
    tags: ["education", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("West", 34),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "The earth is patient, but it does not forget.",
    tags: ["justice", "consequence"],
    source: "Traditional",
  },
  {
    id: makeId("West", 35),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "The rain wets the leopard’s skin but does not wash out the spots.",
    tags: ["character", "identity"],
    source: "Traditional",
  },
  {
    id: makeId("West", 36),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "What an elder sees sitting down, a youth cannot see standing up.",
    tags: ["wisdom", "elders"],
    source: "Traditional",
  },
  {
    id: makeId("West", 37),
    region: "West",
    country: "Ghana",
    origin: "Akan",
    author: "Akan Proverb",
    text: "If you do not know death, look at the grave.",
    tags: ["mortality", "reflection"],
    source: "Traditional",
  },
  {
    id: makeId("West", 38),
    region: "West",
    country: "Nigeria",
    origin: "Igbo",
    author: "Igbo Proverb",
    text: "A man who pays respect to the great paves the way for his own greatness.",
    tags: ["respect", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("West", 39),
    region: "West",
    country: "Senegal",
    origin: "Wolof",
    author: "Wolof Proverb",
    text: "The hyena with a cub does not swallow bones.",
    tags: ["responsibility", "family"],
    source: "Traditional",
  },
  {
    id: makeId("West", 40),
    region: "West",
    country: "Nigeria",
    origin: "Yoruba",
    author: "Yoruba Proverb",
    text: "The stream that forgets its source will dry up.",
    tags: ["roots", "identity"],
    source: "Traditional",
  },

  // EAST (40)
  {
    id: makeId("East", 1),
    region: "East",
    country: "Kenya",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "Haste has no blessing.",
    tags: ["patience", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("East", 2),
    region: "East",
    country: "Tanzania",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "Little by little fills the measure.",
    tags: ["consistency", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("East", 3),
    region: "East",
    country: "Ethiopia",
    origin: "Amharic",
    author: "Amharic Proverb",
    text: "A house without a child is a grave.",
    tags: ["family", "life"],
    source: "Traditional",
  },
  {
    id: makeId("East", 4),
    region: "East",
    country: "Uganda",
    origin: "Luganda",
    author: "Luganda Proverb",
    text: "Where there is love, there is no darkness.",
    tags: ["love", "hope"],
    source: "Traditional",
  },
  {
    id: makeId("East", 5),
    region: "East",
    country: "Somalia",
    origin: "Somali",
    author: "Somali Proverb",
    text: "A man who does not travel thinks his mother is the best cook.",
    tags: ["perspective", "experience"],
    source: "Traditional",
  },
  {
    id: makeId("East", 6),
    region: "East",
    country: "Ethiopia",
    origin: "Oromo",
    author: "Oromo Proverb",
    text: "The person who tells the stories rules the world.",
    tags: ["storytelling", "power"],
    source: "Traditional",
  },
  {
    id: makeId("East", 7),
    region: "East",
    country: "Rwanda",
    origin: "Kinyarwanda",
    author: "Rwandan Proverb",
    text: "The bad branch spoils the whole tree.",
    tags: ["character", "consequence"],
    source: "Traditional",
  },
  {
    id: makeId("East", 8),
    region: "East",
    country: "Burundi",
    origin: "Kirundi",
    author: "Burundian Proverb",
    text: "Even the tallest tree begins as a seed.",
    tags: ["growth", "humility"],
    source: "Traditional",
  },
  {
    id: makeId("East", 9),
    region: "East",
    country: "Kenya",
    origin: "Kikuyu",
    author: "Kikuyu Proverb",
    text: "A single log does not make a bridge.",
    tags: ["cooperation", "community"],
    source: "Traditional",
  },
  {
    id: makeId("East", 10),
    region: "East",
    country: "Tanzania",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "Unity is strength, division is weakness.",
    tags: ["unity", "community"],
    source: "Traditional",
  },
  {
    id: makeId("East", 11),
    region: "East",
    country: "Ethiopia",
    origin: "Amharic",
    author: "Amharic Proverb",
    text: "The fool speaks, the wise listens.",
    tags: ["wisdom", "communication"],
    source: "Traditional",
  },
  {
    id: makeId("East", 12),
    region: "East",
    country: "Somalia",
    origin: "Somali",
    author: "Somali Proverb",
    text: "When elephants fight, it is the grass that suffers.",
    tags: ["conflict", "society"],
    source: "Traditional",
  },
  {
    id: makeId("East", 13),
    region: "East",
    country: "Kenya",
    origin: "Luo",
    author: "Luo Proverb",
    text: "A guest is never a burden.",
    tags: ["hospitality", "culture"],
    source: "Traditional",
  },
  {
    id: makeId("East", 14),
    region: "East",
    country: "Ethiopia",
    origin: "Tigrinya",
    author: "Tigrinya Proverb",
    text: "He who hides his illness cannot expect to be cured.",
    tags: ["honesty", "health"],
    source: "Traditional",
  },
  {
    id: makeId("East", 15),
    region: "East",
    country: "Uganda",
    origin: "Luganda",
    author: "Luganda Proverb",
    text: "A borrowed garment never warms.",
    tags: ["independence", "self-reliance"],
    source: "Traditional",
  },
  {
    id: makeId("East", 16),
    region: "East",
    country: "Rwanda",
    origin: "Kinyarwanda",
    author: "Rwandan Proverb",
    text: "The patient dog eats the fattest bone.",
    tags: ["patience", "reward"],
    source: "Traditional",
  },
  {
    id: makeId("East", 17),
    region: "East",
    country: "Somalia",
    origin: "Somali",
    author: "Somali Proverb",
    text: "Advice is like a seed; whoever plants it will see it grow.",
    tags: ["wisdom", "guidance"],
    source: "Traditional",
  },
  {
    id: makeId("East", 18),
    region: "East",
    country: "Kenya",
    origin: "Kamba",
    author: "Kamba Proverb",
    text: "Rain does not recognize anyone as a friend.",
    tags: ["nature", "reality"],
    source: "Traditional",
  },
  {
    id: makeId("East", 19),
    region: "East",
    country: "Tanzania",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "Better a little sleep than a long regret.",
    tags: ["balance", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("East", 20),
    region: "East",
    country: "Ethiopia",
    origin: "Amharic",
    author: "Amharic Proverb",
    text: "A spider’s web can tie up a lion if it is strong enough.",
    tags: ["unity", "strategy"],
    source: "Traditional",
  },
  {
    id: makeId("East", 21),
    region: "East",
    country: "Uganda",
    origin: "Luganda",
    author: "Luganda Proverb",
    text: "A good name is better than riches.",
    tags: ["reputation", "character"],
    source: "Traditional",
  },
  {
    id: makeId("East", 22),
    region: "East",
    country: "Somalia",
    origin: "Somali",
    author: "Somali Proverb",
    text: "The camel cannot see the crookedness of its own neck.",
    tags: ["self-awareness", "humility"],
    source: "Traditional",
  },
  {
    id: makeId("East", 23),
    region: "East",
    country: "Rwanda",
    origin: "Kinyarwanda",
    author: "Rwandan Proverb",
    text: "He who has not traveled thinks his village is the world.",
    tags: ["perspective", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("East", 24),
    region: "East",
    country: "Kenya",
    origin: "Maasai",
    author: "Maasai Proverb",
    text: "The cow does not forget the calf.",
    tags: ["family", "care"],
    source: "Traditional",
  },
  {
    id: makeId("East", 25),
    region: "East",
    country: "Ethiopia",
    origin: "Oromo",
    author: "Oromo Proverb",
    text: "One who sees does not need to be told.",
    tags: ["awareness", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("East", 26),
    region: "East",
    country: "Tanzania",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "A hurried person drinks tea with a fork.",
    tags: ["patience", "mindfulness"],
    source: "Traditional",
  },
  {
    id: makeId("East", 27),
    region: "East",
    country: "Uganda",
    origin: "Luganda",
    author: "Luganda Proverb",
    text: "The sun does not forget a village just because it is small.",
    tags: ["hope", "equality"],
    source: "Traditional",
  },
  {
    id: makeId("East", 28),
    region: "East",
    country: "Somalia",
    origin: "Somali",
    author: "Somali Proverb",
    text: "A lie has short legs.",
    tags: ["truth", "integrity"],
    source: "Traditional",
  },
  {
    id: makeId("East", 29),
    region: "East",
    country: "Kenya",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "Do not test the depth of a river with both feet.",
    tags: ["caution", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("East", 30),
    region: "East",
    country: "Ethiopia",
    origin: "Amharic",
    author: "Amharic Proverb",
    text: "He who hides his anger builds a fire in his heart.",
    tags: ["emotion", "reflection"],
    source: "Traditional",
  },
  {
    id: makeId("East", 31),
    region: "East",
    country: "Rwanda",
    origin: "Kinyarwanda",
    author: "Rwandan Proverb",
    text: "A tree is known by its fruit.",
    tags: ["character", "results"],
    source: "Traditional",
  },
  {
    id: makeId("East", 32),
    region: "East",
    country: "Uganda",
    origin: "Luganda",
    author: "Luganda Proverb",
    text: "Even the smallest light shines in darkness.",
    tags: ["hope", "courage"],
    source: "Traditional",
  },
  {
    id: makeId("East", 33),
    region: "East",
    country: "Kenya",
    origin: "Luo",
    author: "Luo Proverb",
    text: "A leader does not eat alone.",
    tags: ["leadership", "community"],
    source: "Traditional",
  },
  {
    id: makeId("East", 34),
    region: "East",
    country: "Tanzania",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "One finger cannot wash the face.",
    tags: ["unity", "cooperation"],
    source: "Traditional",
  },
  {
    id: makeId("East", 35),
    region: "East",
    country: "Tanzania",
    origin: "Swahili",
    author: "Swahili Proverb",
    text: "A boat does not go forward if each one is rowing their own way.",
    tags: ["unity", "teamwork"],
    source: "Traditional",
  },
  {
    id: makeId("East", 36),
    region: "East",
    country: "Ethiopia",
    origin: "Oromo",
    author: "Oromo Proverb",
    text: "A wise person does not fall twice into the same hole.",
    tags: ["wisdom", "learning"],
    source: "Traditional",
  },
  {
    id: makeId("East", 37),
    region: "East",
    country: "Kenya",
    origin: "Maasai",
    author: "Maasai Proverb",
    text: "The one who plants trees loves others besides himself.",
    tags: ["legacy", "community"],
    source: "Traditional",
  },
  {
    id: makeId("East", 38),
    region: "East",
    country: "Uganda",
    origin: "Luganda",
    author: "Luganda Proverb",
    text: "The ear that listens is wiser than the mouth that speaks.",
    tags: ["wisdom", "listening"],
    source: "Traditional",
  },
  {
    id: makeId("East", 39),
    region: "East",
    country: "Rwanda",
    origin: "Kinyarwanda",
    author: "Rwandan Proverb",
    text: "He who asks questions cannot avoid answers.",
    tags: ["curiosity", "learning"],
    source: "Traditional",
  },
  {
    id: makeId("East", 40),
    region: "East",
    country: "Ethiopia",
    origin: "Amharic",
    author: "Amharic Proverb",
    text: "The day you are born, the day you die, and the day you understand why.",
    tags: ["life", "reflection"],
    source: "Traditional",
  },

  // NORTH (40)
  {
    id: makeId("North", 1),
    region: "North",
    country: "Morocco",
    origin: "Amazigh (Berber)",
    author: "Amazigh Proverb",
    text: "Silence is the fence around wisdom.",
    tags: ["wisdom", "restraint"],
    source: "Traditional",
  },
  {
    id: makeId("North", 2),
    region: "North",
    country: "Egypt",
    origin: "Arabic",
    author: "Egyptian Proverb",
    text: "He who fears something gives it power.",
    tags: ["courage", "mindset"],
    source: "Traditional",
  },
  {
    id: makeId("North", 3),
    region: "North",
    country: "Algeria",
    origin: "Arabic",
    author: "Algerian Proverb",
    text: "The hand you cannot bite, kiss it.",
    tags: ["strategy", "survival"],
    source: "Traditional",
  },
  {
    id: makeId("North", 4),
    region: "North",
    country: "Tunisia",
    origin: "Arabic",
    author: "Tunisian Proverb",
    text: "Trust in God, but tie your camel.",
    tags: ["responsibility", "prudence"],
    source: "Traditional",
  },
  {
    id: makeId("North", 5),
    region: "North",
    country: "Libya",
    origin: "Arabic",
    author: "Libyan Proverb",
    text: "A closed mouth catches no flies.",
    tags: ["restraint", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("North", 6),
    region: "North",
    country: "Sudan",
    origin: "Arabic",
    author: "Sudanese Proverb",
    text: "A word once spoken cannot return to the mouth.",
    tags: ["speech", "consequence"],
    source: "Traditional",
  },
  {
    id: makeId("North", 7),
    region: "North",
    country: "Morocco",
    origin: "Arabic",
    author: "Moroccan Proverb",
    text: "Whoever knocks at a door must be ready to hear the answer.",
    tags: ["accountability", "courage"],
    source: "Traditional",
  },
  {
    id: makeId("North", 8),
    region: "North",
    country: "Egypt",
    origin: "Arabic",
    author: "Egyptian Proverb",
    text: "The dog barks, but the caravan moves on.",
    tags: ["focus", "resilience"],
    source: "Traditional",
  },
  {
    id: makeId("North", 9),
    region: "North",
    country: "Algeria",
    origin: "Amazigh (Kabyle)",
    author: "Kabyle Proverb",
    text: "The truth does not get lost, even if it is delayed.",
    tags: ["truth", "patience"],
    source: "Traditional",
  },
  {
    id: makeId("North", 10),
    region: "North",
    country: "Tunisia",
    origin: "Arabic",
    author: "Tunisian Proverb",
    text: "A friend is known in times of hardship.",
    tags: ["friendship", "loyalty"],
    source: "Traditional",
  },
  {
    id: makeId("North", 11),
    region: "North",
    country: "Libya",
    origin: "Arabic",
    author: "Libyan Proverb",
    text: "When the house is burning, do not argue about the smoke.",
    tags: ["priorities", "crisis"],
    source: "Traditional",
  },
  {
    id: makeId("North", 12),
    region: "North",
    country: "Sudan",
    origin: "Arabic",
    author: "Sudanese Proverb",
    text: "The patient one sees what the hurried one misses.",
    tags: ["patience", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("North", 13),
    region: "North",
    country: "Morocco",
    origin: "Amazigh (Berber)",
    author: "Amazigh Proverb",
    text: "The wound of words is deeper than the wound of a knife.",
    tags: ["speech", "harm"],
    source: "Traditional",
  },
  {
    id: makeId("North", 14),
    region: "North",
    country: "Egypt",
    origin: "Arabic",
    author: "Egyptian Proverb",
    text: "If you want to be obeyed, command what is possible.",
    tags: ["leadership", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("North", 15),
    region: "North",
    country: "Algeria",
    origin: "Arabic",
    author: "Algerian Proverb",
    text: "He who has health has hope, and he who has hope has everything.",
    tags: ["health", "hope"],
    source: "Traditional",
  },
  {
    id: makeId("North", 16),
    region: "North",
    country: "Tunisia",
    origin: "Arabic",
    author: "Tunisian Proverb",
    text: "A small hole can sink a great ship.",
    tags: ["risk", "awareness"],
    source: "Traditional",
  },
  {
    id: makeId("North", 17),
    region: "North",
    country: "Libya",
    origin: "Arabic",
    author: "Libyan Proverb",
    text: "The one who lies down with dogs wakes up with fleas.",
    tags: ["choices", "character"],
    source: "Traditional",
  },
  {
    id: makeId("North", 18),
    region: "North",
    country: "Sudan",
    origin: "Arabic",
    author: "Sudanese Proverb",
    text: "If you keep company with the wise, you become wise.",
    tags: ["influence", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("North", 19),
    region: "North",
    country: "Morocco",
    origin: "Arabic",
    author: "Moroccan Proverb",
    text: "The heart cannot be washed with words.",
    tags: ["healing", "truth"],
    source: "Traditional",
  },
  {
    id: makeId("North", 20),
    region: "North",
    country: "Egypt",
    origin: "Arabic",
    author: "Egyptian Proverb",
    text: "A book is like a garden carried in the pocket.",
    tags: ["learning", "education"],
    source: "Traditional",
  },
  {
    id: makeId("North", 21),
    region: "North",
    country: "Algeria",
    origin: "Amazigh (Kabyle)",
    author: "Kabyle Proverb",
    text: "He who is afraid of falling will never climb.",
    tags: ["courage", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("North", 22),
    region: "North",
    country: "Tunisia",
    origin: "Arabic",
    author: "Tunisian Proverb",
    text: "One who is full does not believe the hungry.",
    tags: ["empathy", "perspective"],
    source: "Traditional",
  },
  {
    id: makeId("North", 23),
    region: "North",
    country: "Libya",
    origin: "Arabic",
    author: "Libyan Proverb",
    text: "Do not count tomorrow’s bread while today’s oven is cold.",
    tags: ["planning", "reality"],
    source: "Traditional",
  },
  {
    id: makeId("North", 24),
    region: "North",
    country: "Sudan",
    origin: "Arabic",
    author: "Sudanese Proverb",
    text: "The rope of patience has no knots.",
    tags: ["patience", "endurance"],
    source: "Traditional",
  },
  {
    id: makeId("North", 25),
    region: "North",
    country: "Morocco",
    origin: "Arabic",
    author: "Moroccan Proverb",
    text: "A guest brings ten blessings; one he eats, nine he leaves behind.",
    tags: ["hospitality", "culture"],
    source: "Traditional",
  },
  {
    id: makeId("North", 26),
    region: "North",
    country: "Egypt",
    origin: "Arabic",
    author: "Egyptian Proverb",
    text: "A thousand friends are too few; one enemy is too many.",
    tags: ["friendship", "conflict"],
    source: "Traditional",
  },
  {
    id: makeId("North", 27),
    region: "North",
    country: "Algeria",
    origin: "Arabic",
    author: "Algerian Proverb",
    text: "The tongue is small, but it can break bones.",
    tags: ["speech", "power"],
    source: "Traditional",
  },
  {
    id: makeId("North", 28),
    region: "North",
    country: "Tunisia",
    origin: "Arabic",
    author: "Tunisian Proverb",
    text: "He who has no one to blame blames the wind.",
    tags: ["accountability", "character"],
    source: "Traditional",
  },
  {
    id: makeId("North", 29),
    region: "North",
    country: "Libya",
    origin: "Arabic",
    author: "Libyan Proverb",
    text: "If you speak, let your words be better than silence.",
    tags: ["wisdom", "communication"],
    source: "Traditional",
  },
  {
    id: makeId("North", 30),
    region: "North",
    country: "Sudan",
    origin: "Arabic",
    author: "Sudanese Proverb",
    text: "A gentle answer can open an iron door.",
    tags: ["kindness", "communication"],
    source: "Traditional",
  },
  {
    id: makeId("North", 31),
    region: "North",
    country: "Morocco",
    origin: "Amazigh (Berber)",
    author: "Amazigh Proverb",
    text: "A shared burden is half a burden.",
    tags: ["community", "support"],
    source: "Traditional",
  },
  {
    id: makeId("North", 32),
    region: "North",
    country: "Egypt",
    origin: "Arabic",
    author: "Egyptian Proverb",
    text: "An inch of movement is better than a mile of intention.",
    tags: ["action", "discipline"],
    source: "Traditional",
  },
  {
    id: makeId("North", 33),
    region: "North",
    country: "Algeria",
    origin: "Amazigh (Kabyle)",
    author: "Kabyle Proverb",
    text: "The mountain does not laugh at the stone.",
    tags: ["humility", "respect"],
    source: "Traditional",
  },
  {
    id: makeId("North", 34),
    region: "North",
    country: "Tunisia",
    origin: "Arabic",
    author: "Tunisian Proverb",
    text: "The key to the heart is patience.",
    tags: ["patience", "relationships"],
    source: "Traditional",
  },
  {
    id: makeId("North", 35),
    region: "North",
    country: "Libya",
    origin: "Arabic",
    author: "Libyan Proverb",
    text: "The eye may see far, but it cannot see itself.",
    tags: ["self-awareness", "humility"],
    source: "Traditional",
  },
  {
    id: makeId("North", 36),
    region: "North",
    country: "Sudan",
    origin: "Arabic",
    author: "Sudanese Proverb",
    text: "A thorn in the hand is better than a thorn in the foot.",
    tags: ["choices", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("North", 37),
    region: "North",
    country: "Morocco",
    origin: "Arabic",
    author: "Moroccan Proverb",
    text: "The one who tries to please everyone ends up pleasing no one.",
    tags: ["boundaries", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("North", 38),
    region: "North",
    country: "Egypt",
    origin: "Arabic",
    author: "Egyptian Proverb",
    text: "The hand that gives is above the hand that takes.",
    tags: ["generosity", "values"],
    source: "Traditional",
  },
  {
    id: makeId("North", 39),
    region: "North",
    country: "Algeria",
    origin: "Arabic",
    author: "Algerian Proverb",
    text: "Whoever plants goodness harvests honor.",
    tags: ["integrity", "reputation"],
    source: "Traditional",
  },
  {
    id: makeId("North", 40),
    region: "North",
    country: "Tunisia",
    origin: "Arabic",
    author: "Tunisian Proverb",
    text: "The wise person makes a bridge out of the word ‘if’.",
    tags: ["wisdom", "problem-solving"],
    source: "Traditional",
  },

  // CENTRAL (40)
  {
    id: makeId("Central", 1),
    region: "Central",
    country: "Cameroon",
    origin: "Traditional",
    author: "Cameroonian Proverb",
    text: "Rain does not fall on one roof alone.",
    tags: ["community", "shared-fate"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 2),
    region: "Central",
    country: "DR Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A single hand cannot tie a bundle.",
    tags: ["cooperation", "unity"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 3),
    region: "Central",
    country: "Gabon",
    origin: "Traditional",
    author: "Gabonese Proverb",
    text: "The forest answers with echoes what you shout into it.",
    tags: ["consequence", "character"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 4),
    region: "Central",
    country: "Republic of the Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "The drum beats for those who can dance.",
    tags: ["readiness", "opportunity"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 5),
    region: "Central",
    country: "Central African Republic",
    origin: "Traditional",
    author: "Central African Proverb",
    text: "A road is made by walking it.",
    tags: ["progress", "action"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 6),
    region: "Central",
    country: "Chad",
    origin: "Traditional",
    author: "Chadian Proverb",
    text: "A pot does not boil itself; someone must light the fire.",
    tags: ["effort", "responsibility"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 7),
    region: "Central",
    country: "Cameroon",
    origin: "Traditional",
    author: "Cameroonian Proverb",
    text: "If you close your eyes to facts, you will learn through accidents.",
    tags: ["awareness", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 8),
    region: "Central",
    country: "DR Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A good neighbor is better than a distant brother.",
    tags: ["community", "relationships"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 9),
    region: "Central",
    country: "Gabon",
    origin: "Traditional",
    author: "Gabonese Proverb",
    text: "When you see smoke, there is fire somewhere.",
    tags: ["signal", "discernment"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 10),
    region: "Central",
    country: "Equatorial Guinea",
    origin: "Traditional",
    author: "Equatoguinean Proverb",
    text: "A person who has not suffered cannot measure kindness.",
    tags: ["empathy", "perspective"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 11),
    region: "Central",
    country: "Republic of the Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "The one who is carried does not know how far the town is.",
    tags: ["gratitude", "perspective"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 12),
    region: "Central",
    country: "Central African Republic",
    origin: "Traditional",
    author: "Central African Proverb",
    text: "A tree leans on another tree to stand.",
    tags: ["support", "community"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 13),
    region: "Central",
    country: "Chad",
    origin: "Traditional",
    author: "Chadian Proverb",
    text: "The camel does not laugh at the donkey’s load.",
    tags: ["humility", "respect"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 14),
    region: "Central",
    country: "Cameroon",
    origin: "Traditional",
    author: "Cameroonian Proverb",
    text: "A patient person eats ripe fruit.",
    tags: ["patience", "reward"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 15),
    region: "Central",
    country: "DR Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A warning is better than a beating.",
    tags: ["wisdom", "learning"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 16),
    region: "Central",
    country: "Gabon",
    origin: "Traditional",
    author: "Gabonese Proverb",
    text: "The bird that stays on the ground will never know the sky.",
    tags: ["courage", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 17),
    region: "Central",
    country: "Republic of the Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A shared meal tastes better.",
    tags: ["community", "hospitality"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 18),
    region: "Central",
    country: "Central African Republic",
    origin: "Traditional",
    author: "Central African Proverb",
    text: "You do not wipe tears with a knife.",
    tags: ["kindness", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 19),
    region: "Central",
    country: "Chad",
    origin: "Traditional",
    author: "Chadian Proverb",
    text: "A small ant can make a big hill.",
    tags: ["consistency", "impact"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 20),
    region: "Central",
    country: "Cameroon",
    origin: "Traditional",
    author: "Cameroonian Proverb",
    text: "He who hides a wound hides the cure.",
    tags: ["honesty", "healing"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 21),
    region: "Central",
    country: "DR Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "Where water is shallow, stones show themselves.",
    tags: ["truth", "discernment"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 22),
    region: "Central",
    country: "Gabon",
    origin: "Traditional",
    author: "Gabonese Proverb",
    text: "The path is made clear by those who walk it first.",
    tags: ["leadership", "example"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 23),
    region: "Central",
    country: "Republic of the Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A person’s shadow follows them everywhere.",
    tags: ["accountability", "reputation"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 24),
    region: "Central",
    country: "Central African Republic",
    origin: "Traditional",
    author: "Central African Proverb",
    text: "The stick that beats the child also beats the parent.",
    tags: ["consequence", "family"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 25),
    region: "Central",
    country: "Chad",
    origin: "Traditional",
    author: "Chadian Proverb",
    text: "The fastest runner still needs breath.",
    tags: ["balance", "endurance"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 26),
    region: "Central",
    country: "Cameroon",
    origin: "Traditional",
    author: "Cameroonian Proverb",
    text: "If you want to go far, walk with others.",
    tags: ["teamwork", "journey"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 27),
    region: "Central",
    country: "DR Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A mouth that bites its tongue learns caution.",
    tags: ["speech", "restraint"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 28),
    region: "Central",
    country: "Gabon",
    origin: "Traditional",
    author: "Gabonese Proverb",
    text: "A crooked path can still lead home.",
    tags: ["hope", "perseverance"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 29),
    region: "Central",
    country: "Equatorial Guinea",
    origin: "Traditional",
    author: "Equatoguinean Proverb",
    text: "A calm sea does not make a skilled sailor.",
    tags: ["resilience", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 30),
    region: "Central",
    country: "Republic of the Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A clean heart speaks softly.",
    tags: ["character", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 31),
    region: "Central",
    country: "Central African Republic",
    origin: "Traditional",
    author: "Central African Proverb",
    text: "A promise is a debt.",
    tags: ["integrity", "responsibility"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 32),
    region: "Central",
    country: "Chad",
    origin: "Traditional",
    author: "Chadian Proverb",
    text: "You cannot straighten a tree by shouting at it.",
    tags: ["action", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 33),
    region: "Central",
    country: "Cameroon",
    origin: "Traditional",
    author: "Cameroonian Proverb",
    text: "The one who eats alone dies alone.",
    tags: ["community", "sharing"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 34),
    region: "Central",
    country: "DR Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A river is filled by small streams.",
    tags: ["consistency", "progress"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 35),
    region: "Central",
    country: "Gabon",
    origin: "Traditional",
    author: "Gabonese Proverb",
    text: "The forest has ears.",
    tags: ["caution", "awareness"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 36),
    region: "Central",
    country: "Republic of the Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "A lie can travel, but it cannot build a home.",
    tags: ["truth", "integrity"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 37),
    region: "Central",
    country: "Central African Republic",
    origin: "Traditional",
    author: "Central African Proverb",
    text: "The hand that points also has three fingers pointing back.",
    tags: ["self-awareness", "humility"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 38),
    region: "Central",
    country: "Chad",
    origin: "Traditional",
    author: "Chadian Proverb",
    text: "The goat that wanders finds greener leaves.",
    tags: ["curiosity", "opportunity"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 39),
    region: "Central",
    country: "Cameroon",
    origin: "Traditional",
    author: "Cameroonian Proverb",
    text: "A home is built with many hands.",
    tags: ["community", "cooperation"],
    source: "Traditional",
  },
  {
    id: makeId("Central", 40),
    region: "Central",
    country: "DR Congo",
    origin: "Traditional",
    author: "Congolese Proverb",
    text: "The hunter who chases two antelopes returns hungry.",
    tags: ["focus", "discipline"],
    source: "Traditional",
  },

  // SOUTH (40)
  {
    id: makeId("South", 1),
    region: "South",
    country: "South Africa",
    origin: "Zulu/Xhosa",
    author: "Ubuntu Proverb",
    text: "A person is a person because of other people.",
    tags: ["community", "humanity"],
    source: "Traditional",
  },
  {
    id: makeId("South", 2),
    region: "South",
    country: "Zimbabwe",
    origin: "Shona",
    author: "Shona Proverb",
    text: "One finger cannot crush lice.",
    nativeText: "Chara chimwe hachitswanyi inda.",
    tags: ["unity", "cooperation"],
    source: "Traditional",
  },
  {
    id: makeId("South", 3),
    region: "South",
    country: "Botswana",
    origin: "Tswana",
    author: "Tswana Proverb",
    text: "Knowledge is like a garden; it must be cultivated.",
    tags: ["education", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("South", 4),
    region: "South",
    country: "Namibia",
    origin: "Ovambo",
    author: "Ovambo Proverb",
    text: "The child who asks questions does not get lost.",
    tags: ["learning", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("South", 5),
    region: "South",
    country: "Zambia",
    origin: "Bemba",
    author: "Bemba Proverb",
    text: "A canoe does not know who is king.",
    tags: ["equality", "humility"],
    source: "Traditional",
  },
  {
    id: makeId("South", 6),
    region: "South",
    country: "Malawi",
    origin: "Chewa",
    author: "Chewa Proverb",
    text: "The sun does not forget a village.",
    tags: ["hope", "equality"],
    source: "Traditional",
  },
  {
    id: makeId("South", 7),
    region: "South",
    country: "Zimbabwe",
    origin: "Shona",
    author: "Shona Proverb",
    text: "A homestead without a woman is like a barn without cattle.",
    tags: ["family", "culture"],
    source: "Traditional",
  },
  {
    id: makeId("South", 8),
    region: "South",
    country: "South Africa",
    origin: "Zulu",
    author: "Zulu Proverb",
    text: "The axe forgets; the tree remembers.",
    tags: ["history", "reflection"],
    source: "Traditional",
  },
  {
    id: makeId("South", 9),
    region: "South",
    country: "Botswana",
    origin: "Tswana",
    author: "Tswana Proverb",
    text: "A small spark can burn the whole grassland.",
    tags: ["consequence", "awareness"],
    source: "Traditional",
  },
  {
    id: makeId("South", 10),
    region: "South",
    country: "Zambia",
    origin: "Lozi",
    author: "Lozi Proverb",
    text: "A chief is a chief by the people.",
    tags: ["leadership", "community"],
    source: "Traditional",
  },
  {
    id: makeId("South", 11),
    region: "South",
    country: "Namibia",
    origin: "Herero",
    author: "Herero Proverb",
    text: "A tree is bent while it is still young.",
    tags: ["discipline", "upbringing"],
    source: "Traditional",
  },
  {
    id: makeId("South", 12),
    region: "South",
    country: "Malawi",
    origin: "Chewa",
    author: "Chewa Proverb",
    text: "Rain does not choose where to fall.",
    tags: ["fate", "reality"],
    source: "Traditional",
  },
  {
    id: makeId("South", 13),
    region: "South",
    country: "South Africa",
    origin: "Xhosa",
    author: "Xhosa Proverb",
    text: "Even the strongest wind must rest.",
    tags: ["balance", "rest"],
    source: "Traditional",
  },
  {
    id: makeId("South", 14),
    region: "South",
    country: "Zimbabwe",
    origin: "Shona",
    author: "Shona Proverb",
    text: "The one who carries the basket knows its weight.",
    tags: ["responsibility", "perspective"],
    source: "Traditional",
  },
  {
    id: makeId("South", 15),
    region: "South",
    country: "Botswana",
    origin: "Tswana",
    author: "Tswana Proverb",
    text: "A borrowed axe does not cut well.",
    tags: ["independence", "self-reliance"],
    source: "Traditional",
  },
  {
    id: makeId("South", 16),
    region: "South",
    country: "Zambia",
    origin: "Bemba",
    author: "Bemba Proverb",
    text: "The future belongs to those who prepare today.",
    tags: ["planning", "discipline"],
    source: "Traditional",
  },
  {
    id: makeId("South", 17),
    region: "South",
    country: "Malawi",
    origin: "Chewa",
    author: "Chewa Proverb",
    text: "He who listens understands.",
    tags: ["wisdom", "listening"],
    source: "Traditional",
  },
  {
    id: makeId("South", 18),
    region: "South",
    country: "Namibia",
    origin: "Ovambo",
    author: "Ovambo Proverb",
    text: "A hungry lion does not turn down meat.",
    tags: ["opportunity", "focus"],
    source: "Traditional",
  },
  {
    id: makeId("South", 19),
    region: "South",
    country: "South Africa",
    origin: "Zulu",
    author: "Zulu Proverb",
    text: "Respect is two ways.",
    tags: ["respect"],
    source: "Traditional",
  },
  {
    id: makeId("South", 20),
    region: "South",
    country: "Zimbabwe",
    origin: "Shona",
    author: "Shona Proverb",
    text: "A clever person solves a problem; a wise person avoids it.",
    tags: ["wisdom", "strategy"],
    source: "Traditional",
  },
  {
    id: makeId("South", 21),
    region: "South",
    country: "Botswana",
    origin: "Tswana",
    author: "Tswana Proverb",
    text: "The river is filled by many drops.",
    tags: ["consistency", "progress"],
    source: "Traditional",
  },
  {
    id: makeId("South", 22),
    region: "South",
    country: "Zambia",
    origin: "Lozi",
    author: "Lozi Proverb",
    text: "The mouth that eats does not speak.",
    tags: ["focus", "discipline"],
    source: "Traditional",
  },
  {
    id: makeId("South", 23),
    region: "South",
    country: "Malawi",
    origin: "Chewa",
    author: "Chewa Proverb",
    text: "A child belongs not to one parent but to the community.",
    tags: ["community", "upbringing"],
    source: "Traditional",
  },
  {
    id: makeId("South", 24),
    region: "South",
    country: "Namibia",
    origin: "Herero",
    author: "Herero Proverb",
    text: "The one who plants a tree believes in tomorrow.",
    tags: ["legacy", "hope"],
    source: "Traditional",
  },
  {
    id: makeId("South", 25),
    region: "South",
    country: "South Africa",
    origin: "Xhosa",
    author: "Xhosa Proverb",
    text: "A brave man dies once; a coward dies many times.",
    tags: ["courage", "character"],
    source: "Traditional",
  },
  {
    id: makeId("South", 26),
    region: "South",
    country: "Zimbabwe",
    origin: "Shona",
    author: "Shona Proverb",
    text: "When one goat falls into a ditch, the others learn.",
    tags: ["learning", "consequence"],
    source: "Traditional",
  },
  {
    id: makeId("South", 27),
    region: "South",
    country: "Botswana",
    origin: "Tswana",
    author: "Tswana Proverb",
    text: "The ear that listens gathers wisdom.",
    tags: ["wisdom", "learning"],
    source: "Traditional",
  },
  {
    id: makeId("South", 28),
    region: "South",
    country: "Zambia",
    origin: "Bemba",
    author: "Bemba Proverb",
    text: "Even a small fire can warm a village.",
    tags: ["impact", "community"],
    source: "Traditional",
  },
  {
    id: makeId("South", 29),
    region: "South",
    country: "Malawi",
    origin: "Chewa",
    author: "Chewa Proverb",
    text: "A promise is like a cloud; it disappears if not fulfilled.",
    tags: ["integrity", "responsibility"],
    source: "Traditional",
  },
  {
    id: makeId("South", 30),
    region: "South",
    country: "Namibia",
    origin: "Ovambo",
    author: "Ovambo Proverb",
    text: "The one who walks slowly goes far.",
    tags: ["patience", "perseverance"],
    source: "Traditional",
  },
  {
    id: makeId("South", 31),
    region: "South",
    country: "South Africa",
    origin: "Zulu",
    author: "Zulu Proverb",
    text: "The child who is carried does not know the distance of the journey.",
    tags: ["perspective", "gratitude"],
    source: "Traditional",
  },
  {
    id: makeId("South", 32),
    region: "South",
    country: "Zimbabwe",
    origin: "Shona",
    author: "Shona Proverb",
    text: "The one who fetches water is the one who spills it.",
    tags: ["effort", "responsibility"],
    source: "Traditional",
  },
  {
    id: makeId("South", 33),
    region: "South",
    country: "Botswana",
    origin: "Tswana",
    author: "Tswana Proverb",
    text: "Wisdom does not come overnight.",
    tags: ["growth", "patience"],
    source: "Traditional",
  },
  {
    id: makeId("South", 34),
    region: "South",
    country: "Zambia",
    origin: "Lozi",
    author: "Lozi Proverb",
    text: "A leader without followers is just a walker.",
    tags: ["leadership", "community"],
    source: "Traditional",
  },
  {
    id: makeId("South", 35),
    region: "South",
    country: "Malawi",
    origin: "Chewa",
    author: "Chewa Proverb",
    text: "The earth is patient but not forgetful.",
    tags: ["justice", "consequence"],
    source: "Traditional",
  },
  {
    id: makeId("South", 36),
    region: "South",
    country: "Namibia",
    origin: "Herero",
    author: "Herero Proverb",
    text: "The road that is straight is rarely safe.",
    tags: ["caution", "wisdom"],
    source: "Traditional",
  },
  {
    id: makeId("South", 37),
    region: "South",
    country: "South Africa",
    origin: "Xhosa",
    author: "Xhosa Proverb",
    text: "The one who has milk does not envy the one who has honey.",
    tags: ["contentment", "gratitude"],
    source: "Traditional",
  },
  {
    id: makeId("South", 38),
    region: "South",
    country: "Zimbabwe",
    origin: "Shona",
    author: "Shona Proverb",
    text: "The hyena’s laugh does not mean joy.",
    tags: ["discernment", "awareness"],
    source: "Traditional",
  },
  {
    id: makeId("South", 39),
    region: "South",
    country: "Botswana",
    origin: "Tswana",
    author: "Tswana Proverb",
    text: "The one who stands still is overtaken.",
    tags: ["progress", "growth"],
    source: "Traditional",
  },
  {
    id: makeId("South", 40),
    region: "South",
    country: "Zambia",
    origin: "Bemba",
    author: "Bemba Proverb",
    text: "Even the longest journey begins with a step.",
    tags: ["journey", "action"],
    source: "Traditional",
  },
];
